
export default  {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        Routes: Symbol("Routes"),
        Index: Symbol("Index"),
        SubmitUsernameService: Symbol("SubmitUsernameService"),
        SubmitUsernameController: Symbol("SubmitUsernameController"),
        LogoutService: Symbol("LogoutServices"),
        IndexController: Symbol("IndexController"),
        SubmitSimpleViewCreationService: Symbol("SubmitSimpleViewCreationService"),
        SubmitGameCreationService: Symbol("SubmitGameCreationService"),
        SubmitGameCreationController: Symbol("SubmitGameCreationController"),
        SubmitSimpleViewCreationController: Symbol("SubmitSimpleViewCreationController"),
        FreeViewService: Symbol("FreeViewService"),
        Position: Symbol("Position"),
        SubmitFreeViewCreationService: Symbol("SubmitSimpleViewCreationService"),
        SubmitFreeViewCreationController: Symbol("SubmitSimpleViewCreationController"),
        IdentifacationErrController: Symbol("IdentificationErrController"),
        IdentifacationErr: Symbol("IdentifcationErr"),
        ErrorsReplacementController: Symbol("ErrorsReplacementController"),
        ErrorsReplacement: Symbol("ErrorsReplacement"),
        GetGamesController: Symbol("GetGamesController"),
        GetGamesService: Symbol("GetGamesService"),
        DuplicateImagesController: Symbol("DuplicateImagesController"),
        HighScoreService: Symbol("HighScoreService"),
        HighScoreController: Symbol("HighScoreController"),
        GeometricConverter: Symbol("GeometricConverter"),
        ThematicSceneConverter: Symbol("ThematicSceneConverter"),
        DeleteImageController: Symbol("DeleteImageController"),
        GameStatusController: Symbol("GameStatusController"),
};
